export const data = [
  {
    id: 507032567,
    node_id: 'R_kgDOHjiz9w',
    name: 'agario-clone',
    full_name: 'Max-im/agario-clone',
    private: false,
    owner: {
      login: 'Max-im',
      id: 12202021,
      node_id: 'MDQ6VXNlcjEyMjAyMDIx',
      avatar_url: 'https://avatars.githubusercontent.com/u/12202021?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Max-im',
      html_url: 'https://github.com/Max-im',
      followers_url: 'https://api.github.com/users/Max-im/followers',
      following_url: 'https://api.github.com/users/Max-im/following{/other_user}',
      gists_url: 'https://api.github.com/users/Max-im/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Max-im/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Max-im/subscriptions',
      organizations_url: 'https://api.github.com/users/Max-im/orgs',
      repos_url: 'https://api.github.com/users/Max-im/repos',
      events_url: 'https://api.github.com/users/Max-im/events{/privacy}',
      received_events_url: 'https://api.github.com/users/Max-im/received_events',
      type: 'User',
      site_admin: false,
    },
    html_url: 'https://github.com/Max-im/agario-clone',
    description: 'Favorit Canvas Game Agar.io clone',
    fork: false,
    url: 'https://api.github.com/repos/Max-im/agario-clone',
    forks_url: 'https://api.github.com/repos/Max-im/agario-clone/forks',
    keys_url: 'https://api.github.com/repos/Max-im/agario-clone/keys{/key_id}',
    collaborators_url:
      'https://api.github.com/repos/Max-im/agario-clone/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/Max-im/agario-clone/teams',
    hooks_url: 'https://api.github.com/repos/Max-im/agario-clone/hooks',
    issue_events_url: 'https://api.github.com/repos/Max-im/agario-clone/issues/events{/number}',
    events_url: 'https://api.github.com/repos/Max-im/agario-clone/events',
    assignees_url: 'https://api.github.com/repos/Max-im/agario-clone/assignees{/user}',
    branches_url: 'https://api.github.com/repos/Max-im/agario-clone/branches{/branch}',
    tags_url: 'https://api.github.com/repos/Max-im/agario-clone/tags',
    blobs_url: 'https://api.github.com/repos/Max-im/agario-clone/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/Max-im/agario-clone/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/Max-im/agario-clone/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/Max-im/agario-clone/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/Max-im/agario-clone/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/Max-im/agario-clone/languages',
    stargazers_url: 'https://api.github.com/repos/Max-im/agario-clone/stargazers',
    contributors_url: 'https://api.github.com/repos/Max-im/agario-clone/contributors',
    subscribers_url: 'https://api.github.com/repos/Max-im/agario-clone/subscribers',
    subscription_url: 'https://api.github.com/repos/Max-im/agario-clone/subscription',
    commits_url: 'https://api.github.com/repos/Max-im/agario-clone/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/Max-im/agario-clone/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/Max-im/agario-clone/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/Max-im/agario-clone/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/Max-im/agario-clone/contents/{+path}',
    compare_url: 'https://api.github.com/repos/Max-im/agario-clone/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/Max-im/agario-clone/merges',
    archive_url: 'https://api.github.com/repos/Max-im/agario-clone/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/Max-im/agario-clone/downloads',
    issues_url: 'https://api.github.com/repos/Max-im/agario-clone/issues{/number}',
    pulls_url: 'https://api.github.com/repos/Max-im/agario-clone/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/Max-im/agario-clone/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/Max-im/agario-clone/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/Max-im/agario-clone/labels{/name}',
    releases_url: 'https://api.github.com/repos/Max-im/agario-clone/releases{/id}',
    deployments_url: 'https://api.github.com/repos/Max-im/agario-clone/deployments',
    created_at: '2022-06-24T14:04:29Z',
    updated_at: '2022-06-24T14:08:24Z',
    pushed_at: '2022-06-24T14:04:59Z',
    git_url: 'git://github.com/Max-im/agario-clone.git',
    ssh_url: 'git@github.com:Max-im/agario-clone.git',
    clone_url: 'https://github.com/Max-im/agario-clone.git',
    svn_url: 'https://github.com/Max-im/agario-clone',
    homepage: '',
    size: 2001,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ['socket-io', '#game'],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
  },
  // {
  //   id: 190203892,
  //   node_id: 'MDEwOlJlcG9zaXRvcnkxOTAyMDM4OTI=',
  //   name: 'postgresSQL-sample',
  //   full_name: 'Max-im/postgresSQL-sample',
  //   private: false,
  //   owner: {
  //     login: 'Max-im',
  //     id: 12202021,
  //     node_id: 'MDQ6VXNlcjEyMjAyMDIx',
  //     avatar_url: 'https://avatars.githubusercontent.com/u/12202021?v=4',
  //     gravatar_id: '',
  //     url: 'https://api.github.com/users/Max-im',
  //     html_url: 'https://github.com/Max-im',
  //     followers_url: 'https://api.github.com/users/Max-im/followers',
  //     following_url: 'https://api.github.com/users/Max-im/following{/other_user}',
  //     gists_url: 'https://api.github.com/users/Max-im/gists{/gist_id}',
  //     starred_url: 'https://api.github.com/users/Max-im/starred{/owner}{/repo}',
  //     subscriptions_url: 'https://api.github.com/users/Max-im/subscriptions',
  //     organizations_url: 'https://api.github.com/users/Max-im/orgs',
  //     repos_url: 'https://api.github.com/users/Max-im/repos',
  //     events_url: 'https://api.github.com/users/Max-im/events{/privacy}',
  //     received_events_url: 'https://api.github.com/users/Max-im/received_events',
  //     type: 'User',
  //     site_admin: false,
  //   },
  //   html_url: 'https://github.com/Max-im/postgresSQL-sample',
  //   description: 'postgresSQL sample',
  //   fork: false,
  //   url: 'https://api.github.com/repos/Max-im/postgresSQL-sample',
  //   forks_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/forks',
  //   keys_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/keys{/key_id}',
  //   collaborators_url:
  //     'https://api.github.com/repos/Max-im/postgresSQL-sample/collaborators{/collaborator}',
  //   teams_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/teams',
  //   hooks_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/hooks',
  //   issue_events_url:
  //     'https://api.github.com/repos/Max-im/postgresSQL-sample/issues/events{/number}',
  //   events_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/events',
  //   assignees_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/assignees{/user}',
  //   branches_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/branches{/branch}',
  //   tags_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/tags',
  //   blobs_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/git/blobs{/sha}',
  //   git_tags_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/git/tags{/sha}',
  //   git_refs_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/git/refs{/sha}',
  //   trees_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/git/trees{/sha}',
  //   statuses_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/statuses/{sha}',
  //   languages_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/languages',
  //   stargazers_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/stargazers',
  //   contributors_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/contributors',
  //   subscribers_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/subscribers',
  //   subscription_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/subscription',
  //   commits_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/commits{/sha}',
  //   git_commits_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/git/commits{/sha}',
  //   comments_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/comments{/number}',
  //   issue_comment_url:
  //     'https://api.github.com/repos/Max-im/postgresSQL-sample/issues/comments{/number}',
  //   contents_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/contents/{+path}',
  //   compare_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/compare/{base}...{head}',
  //   merges_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/merges',
  //   archive_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/{archive_format}{/ref}',
  //   downloads_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/downloads',
  //   issues_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/issues{/number}',
  //   pulls_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/pulls{/number}',
  //   milestones_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/milestones{/number}',
  //   notifications_url:
  //     'https://api.github.com/repos/Max-im/postgresSQL-sample/notifications{?since,all,participating}',
  //   labels_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/labels{/name}',
  //   releases_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/releases{/id}',
  //   deployments_url: 'https://api.github.com/repos/Max-im/postgresSQL-sample/deployments',
  //   created_at: '2019-06-04T13:10:19Z',
  //   updated_at: '2022-06-20T12:55:34Z',
  //   pushed_at: '2022-07-07T05:54:29Z',
  //   git_url: 'git://github.com/Max-im/postgresSQL-sample.git',
  //   ssh_url: 'git@github.com:Max-im/postgresSQL-sample.git',
  //   clone_url: 'https://github.com/Max-im/postgresSQL-sample.git',
  //   svn_url: 'https://github.com/Max-im/postgresSQL-sample',
  //   homepage: '',
  //   size: 398,
  //   stargazers_count: 0,
  //   watchers_count: 0,
  //   language: 'JavaScript',
  //   has_issues: true,
  //   has_projects: true,
  //   has_downloads: true,
  //   has_wiki: true,
  //   has_pages: false,
  //   forks_count: 0,
  //   mirror_url: null,
  //   archived: false,
  //   disabled: false,
  //   open_issues_count: 9,
  //   license: null,
  //   allow_forking: true,
  //   is_template: false,
  //   web_commit_signoff_required: false,
  //   topics: ['node', 'postgresql'],
  //   visibility: 'public',
  //   forks: 0,
  //   open_issues: 9,
  //   watchers: 0,
  //   default_branch: 'master',
  // },
];
